export const AWAITING_RETRIEVE_DATA = "AWAITNG_RETRIEVE_DATA";
export const SUCCESS_RETRIEVE_DATA = "SUCCESS_RETRIEVE_DATA";
export const FAILED_RETRIEVE_DATA = "FAILED_RETRIEVE_DATA";
export const SUCCESS_RETRIEVE_USER = "SUCCESS_RETRIEVE_USER";
export const FAILED_RETRIEVE_USER = "FAILED_RETRIEVE_USER";
